global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8080']

  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://internal.elsons.co.uk
          - https://grafana.elsons.co.uk
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        target_label: instance

  - job_name: redis
    static_configs:
      - targets: ['redis_exporter:9121']
